// Generated by gencpp from file digits/CountRequest.msg
// DO NOT EDIT!


#ifndef DIGITS_MESSAGE_COUNTREQUEST_H
#define DIGITS_MESSAGE_COUNTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace digits
{
template <class ContainerAllocator>
struct CountRequest_
{
  typedef CountRequest_<ContainerAllocator> Type;

  CountRequest_()
    {
    }
  CountRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::digits::CountRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::digits::CountRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CountRequest_

typedef ::digits::CountRequest_<std::allocator<void> > CountRequest;

typedef boost::shared_ptr< ::digits::CountRequest > CountRequestPtr;
typedef boost::shared_ptr< ::digits::CountRequest const> CountRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::digits::CountRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::digits::CountRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace digits

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::digits::CountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::digits::CountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::CountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::CountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::CountRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::CountRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::digits::CountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::digits::CountRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::digits::CountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "digits/CountRequest";
  }

  static const char* value(const ::digits::CountRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::digits::CountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::digits::CountRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::digits::CountRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::digits::CountRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::digits::CountRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DIGITS_MESSAGE_COUNTREQUEST_H
