// Generated by gencpp from file digits/CountResponse.msg
// DO NOT EDIT!


#ifndef DIGITS_MESSAGE_COUNTRESPONSE_H
#define DIGITS_MESSAGE_COUNTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace digits
{
template <class ContainerAllocator>
struct CountResponse_
{
  typedef CountResponse_<ContainerAllocator> Type;

  CountResponse_()
    : count(0)
    , timestamp()  {
    }
  CountResponse_(const ContainerAllocator& _alloc)
    : count(0)
    , timestamp()  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::digits::CountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::digits::CountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CountResponse_

typedef ::digits::CountResponse_<std::allocator<void> > CountResponse;

typedef boost::shared_ptr< ::digits::CountResponse > CountResponsePtr;
typedef boost::shared_ptr< ::digits::CountResponse const> CountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::digits::CountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::digits::CountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::digits::CountResponse_<ContainerAllocator1> & lhs, const ::digits::CountResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::digits::CountResponse_<ContainerAllocator1> & lhs, const ::digits::CountResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace digits

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::digits::CountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::digits::CountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::CountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::CountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::CountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::CountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::digits::CountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74eb533b32c09c7c3df3f24d5d8745d4";
  }

  static const char* value(const ::digits::CountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74eb533b32c09c7cULL;
  static const uint64_t static_value2 = 0x3df3f24d5d8745d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::digits::CountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "digits/CountResponse";
  }

  static const char* value(const ::digits::CountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::digits::CountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 count\n"
"time timestamp\n"
;
  }

  static const char* value(const ::digits::CountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::digits::CountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::digits::CountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::digits::CountResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIGITS_MESSAGE_COUNTRESPONSE_H
