// Generated by gencpp from file digits/Count.msg
// DO NOT EDIT!


#ifndef DIGITS_MESSAGE_COUNT_H
#define DIGITS_MESSAGE_COUNT_H

#include <ros/service_traits.h>


#include <digits/CountRequest.h>
#include <digits/CountResponse.h>


namespace digits
{

struct Count
{

typedef CountRequest Request;
typedef CountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Count
} // namespace digits


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::digits::Count > {
  static const char* value()
  {
    return "74eb533b32c09c7c3df3f24d5d8745d4";
  }

  static const char* value(const ::digits::Count&) { return value(); }
};

template<>
struct DataType< ::digits::Count > {
  static const char* value()
  {
    return "digits/Count";
  }

  static const char* value(const ::digits::Count&) { return value(); }
};


// service_traits::MD5Sum< ::digits::CountRequest> should match
// service_traits::MD5Sum< ::digits::Count >
template<>
struct MD5Sum< ::digits::CountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::digits::Count >::value();
  }
  static const char* value(const ::digits::CountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::digits::CountRequest> should match
// service_traits::DataType< ::digits::Count >
template<>
struct DataType< ::digits::CountRequest>
{
  static const char* value()
  {
    return DataType< ::digits::Count >::value();
  }
  static const char* value(const ::digits::CountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::digits::CountResponse> should match
// service_traits::MD5Sum< ::digits::Count >
template<>
struct MD5Sum< ::digits::CountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::digits::Count >::value();
  }
  static const char* value(const ::digits::CountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::digits::CountResponse> should match
// service_traits::DataType< ::digits::Count >
template<>
struct DataType< ::digits::CountResponse>
{
  static const char* value()
  {
    return DataType< ::digits::Count >::value();
  }
  static const char* value(const ::digits::CountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIGITS_MESSAGE_COUNT_H
