// Generated by gencpp from file digits/Segments.msg
// DO NOT EDIT!


#ifndef DIGITS_MESSAGE_SEGMENTS_H
#define DIGITS_MESSAGE_SEGMENTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace digits
{
template <class ContainerAllocator>
struct Segments_
{
  typedef Segments_<ContainerAllocator> Type;

  Segments_()
    : digit(0)
    , segments()  {
    }
  Segments_(const ContainerAllocator& _alloc)
    : digit(0)
    , segments(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _digit_type;
  _digit_type digit;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _segments_type;
  _segments_type segments;





  typedef boost::shared_ptr< ::digits::Segments_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::digits::Segments_<ContainerAllocator> const> ConstPtr;

}; // struct Segments_

typedef ::digits::Segments_<std::allocator<void> > Segments;

typedef boost::shared_ptr< ::digits::Segments > SegmentsPtr;
typedef boost::shared_ptr< ::digits::Segments const> SegmentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::digits::Segments_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::digits::Segments_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::digits::Segments_<ContainerAllocator1> & lhs, const ::digits::Segments_<ContainerAllocator2> & rhs)
{
  return lhs.digit == rhs.digit &&
    lhs.segments == rhs.segments;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::digits::Segments_<ContainerAllocator1> & lhs, const ::digits::Segments_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace digits

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::digits::Segments_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::digits::Segments_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::Segments_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digits::Segments_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::Segments_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digits::Segments_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::digits::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52224b55a09fd5047a73d23a18410ec0";
  }

  static const char* value(const ::digits::Segments_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52224b55a09fd504ULL;
  static const uint64_t static_value2 = 0x7a73d23a18410ec0ULL;
};

template<class ContainerAllocator>
struct DataType< ::digits::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "digits/Segments";
  }

  static const char* value(const ::digits::Segments_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::digits::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 digit\n"
"uint8[] segments\n"
;
  }

  static const char* value(const ::digits::Segments_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::digits::Segments_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digit);
      stream.next(m.segments);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Segments_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::digits::Segments_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::digits::Segments_<ContainerAllocator>& v)
  {
    s << indent << "digit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.digit);
    s << indent << "segments[]" << std::endl;
    for (size_t i = 0; i < v.segments.size(); ++i)
    {
      s << indent << "  segments[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.segments[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIGITS_MESSAGE_SEGMENTS_H
